version: '3'
services:
  app:
    build:
      context: ./      # Dockerfile保存場所
    image: n-app                  # イメージ名
    container_name: n-app         # コンテナ名
    ports:                          # ポート接続
      - 3000:5000
    environment:
      PORT: 5000

  database:
    image: postgres:9.6
    volumes:
      - ./init-sql:/docker-entrypoint-initdb.d:ro

    environment:
      POSTGRES_DB: youmu
      POSTGRES_HOST_AUTH_METHOD: trust
