version: '3'
services:
  app:
    build:
      context: ./      # Dockerfile保存場所
    depends_on: 
      - database
    image: n-app
    volumes:
     - "./app:/src"
    container_name: n-app         # コンテナ名
    ports:                          # ポート接続
      - 3000:5000
    environment:
      PORT: 5000
      DB_USER: postgres
      DB_PASS: taapp99
      DB_HOST: database
      DB_PORT: 5432
      DB_NAME: mydatabase
    tty: true

  database:
    image: postgres:12.3
    volumes:
      - ./init-sql:/docker-entrypoint-initdb.d:ro
    environment:
      POSTGRES_DB: mydatabase
      TZ: "Asia/Tokyo"
      POSTGRES_HOST_AUTH_METHOD: trust
