version: '3'
services:
  app:
    build:
      context: ./      # Dockerfile保存場所
    image: n-app                  # イメージ名
    container_name: n-app         # コンテナ名
    ports:                          # ポート接続
      - 3000:5000
    # volumes:                        # mount workdir
    #   - ./myapp:/src
    environment:
      PORT: 5000
    # command: [sh, -c, npm install && npm start]
